# Generated by Django 3.0.3 on 2020-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
